[build]
  command = "npm run build" # Ваша команда для сборки проекта, если нужна
  functions = "lambda"
  publish = "public"

[build.environment]
  # Опционально, здесь можно установить переменные окружения, если нужно

[[plugins]]
  package = "@netlify/plugin-nextjs"

[plugins.inputs]
  nextConfigPath = "next.config.js"

# Команда, которая будет выполнена после завершения деплоя
[build.postBuild]
  command = "node afterDeploy.js" # Ваша команда после деплоя
